### ISSUE TITLE
diff display is not fully expanded.

### ISSUE THREAD

**Issue by KK-AL** [smartshark/visualSHARK#29]
There is a problem with the display of the diff where we are supposed to label the changes. The contents (before and after) are displayed as squeezed in narrow margins, and therefore difficult to work with.    
![image](https://user-images.githubusercontent.com/23350294/82716966-df729c80-9cb7-11ea-994d-21853fdae56b.png)

**Comment by atrautsch** [comment]
The display should automatically fill as much screen space as possible. You can remove the right sidebar by clicking on the 3 dashes to the right of the username.
Other than that we only implemented the side by side diff view so there is not a lot we can do about this.
If the diff view does not fill the rest of the screen we may have a display bug somewhere.
In that case we need to know your browser and browser version to try to reproduce it.

**Comment by kk-gndu** [comment]
Firefox version 76.0.1 (64-bit) running on Windows 8.1. I hope it helps.
