### ISSUE TITLE
diffs for the Commit a27b00b9d4c8989e2482e76bbdf2cf80c2436379 are not available. 

### ISSUE THREAD

**Issue by kk-gndu** [smartshark/visualSHARK#30]
While labeling changes in **OPENNLP-471 - DictionaryNameFinder has HASHing  @issues**, I found that diffs for the last commit a27b00b9d4c8989e2482e76bbdf2cf80c2436379 are not available.The submit labels button also did not raise any warning. In fact there was no response. 
Unfortunately, on refresh, I lost all the labels I have already marked for the other commits of this issue.
After refresh, I first checked the last commit. Again no diffs are available for the last commit.
I am stuck now as the interface displays the message "You have not finished labeling the last issue, loading last issue first.", when I try to load another project. 
@sherbold

**Comment by atrautsch** [comment]
Sorry you ran into this issue.
That change contained a .txt file for which we got an invalid encoding error.
I have updated the live system so that it ignores files with encoding errors, you can continue labeling now.
