### ISSUE TITLE
CODEC-187 - Labeling for two lines are not possible by pressing keyboard 

### ISSUE THREAD

**Issue by siminmaleki** [smartshark/visualSHARK#32]
In these files nothing happens when you press 1-7 numbers on keyboard only on the right panel and I have "can not edit in read only editor" but labeling the file works. 

*** Commit 39d5df29fb768fd257f9d328b99f00bc69ec864a

src/main/resources/org/apache/commons/codec/language/bm/gen_exact_arabic.txt
line 18

src/main/resources/org/apache/commons/codec/language/bm/ash_exact_russian.txt
Line 19

**Comment by sherbold** [comment]
Sorry, we overlooked this. Do you still have this issue? Also, did the labeling with right-click work?

**Comment by siminmaleki** [comment]
yes. done. thank you
