### ISSUE TITLE
Deploy visualSHARK

### ISSUE THREAD

**Issue by yiikou** [smartshark/visualSHARK#34]
Hi, I'm trying to deploy visualSHARK, but failed, with mac 10.15.1 and Ubuntu 16.04 LTS. 

On mac 10.15.1, I failed at `python manage.py migrate`.  First time I got `"django.db.utils.OperationalError: (2002, "Can't connect to MySQL server on '127.0.0.1' (36)")"`, and then I realize MySQL need to start before it. While after that, I got `"unknown database visualSHARK"`. And it stucks here... Given the latest readme.md is updated 13 months ago, I wonder that do you have an updated version? Or will the docker solution, or VM solution (like what serverSHARK does) be provided?

On Ubuntu 16.04 LTS. I failed earlier when I try to install npm and python requirement.txt. Will give more try on it.

The SmarkSHARK is a brilliant platform, all the plugin looks promising. I sincerely hope that I could receive any suggestions from you to help me deploy and explore it.

Thank you!

**Comment by atrautsch** [comment]
Hi, sorry about that, the readme really needs more information. The MySQL server needs to be available and the visualSHARK database has to exist. This is not something the migrate command can do because usually the rights of the user does not allow this. After that, migrate can populate the MySQL datbase with the Django and visualSHARK specific tables.

**Comment by yiikou** [comment]
@atrautsch thanks for the explanation! By saying "usually the rights of the user does not allow this" do you mean on the first time, user cannot migrate it due to the lack of db setting? Could you provide more details for the user first time deploy that (the serverSHARK is on already). For example, how do I create visualSHARK db with the proper table?

Thank you!

**Comment by yiikou** [comment]
Would like to double check the configuratio in setting.py, where the host of mongo db is "141.5.113.177", looks magical. Seems I need to change it my db (if I have)?

**Comment by atrautsch** [comment]
The MySQL database for the visualshark has to exist prior to the migration. First you have to create a MySQL Database and a user that has access to the database. This information is then saved in settings.py.
After that you can run manage.py migrate.
The MongoDB Database is of course the host and credentials of your local installation.

**Comment by yiikou** [comment]
Hi @atrautsch, thank you for the help! I can finally deploy and run the frontend! But it is kind of awkward that I cannot log in.. I've tried the user name and password that I created using the "createsuperuser.py" script, and also tried using "guest" that is set in ".env.production.local". What is the correct account for login?

Thank you!!

**Comment by atrautsch** [comment]
Strange, the account to login should be the one from the manage.py createsuperuser as that creates the account.
You can also login to the backend and check if a userprofile has been created by using the superuser to login to localhost:8000/admin.
The guest in .env.production.local is only for the rabbitmq connection, we use the message broker for asynchronous comunication between frontend/backend/worker.
The visualSHARK in most cases only reads from the MongoDB, it only writes if we use it for manually validating existing data.
Maybe the problem is that there is nothing yet in the MongoDB.
The vue frontend does not connect to the database itself it only uses the rest API provided by the backend which itself queries the MySQL or the MongoDB depending on the endpoint.

**Comment by yiikou** [comment]
Hi @atrautsch, I can login now! And yes, there is nothing in MongoDB, and I guess that is the reason why I cannot find my project in serverSHARK and I found that the worker failed. When I tried to ```python manage.py peon```, test_connection_servershark keeps failing.

```
executing job test_connection_servershark
..........
  File "visualSHARK/visualSHARK/management/commands/peon.py", line 43, in consume
    res, msg = r.test_connection(dat['data'])
  File "visualSHARK/visualSHARK/util/remote.py", line 30, in test_connection
    dat = r.json()
  File "visualSHARK/lib/python3.7/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/anaconda3/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/anaconda3/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/anaconda3/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
"""
And here is the data of the job 
```
{
   "ping":"1",
   "api_url":"http://127.0.0.1:8001/remote",
   "api_key":123,
   "substitutions":{
      "db_user":{
         "name":"$db_user",
         "description":"database username"
      },
      "db_password":{
         "name":"$db_password",
         "description":"database password"
      },
      "db_database":{
         "name":"$db_database",
         "description":"database name"
      },
      "db_hostname":{
         "name":"$db_hostname",
         "description":"hostname on which the database runs on"
      },
      "db_port":{
         "name":"$db_port",
         "description":"port on which the database listens"
      },
      "db_authentication":{
         "name":"$db_authentication",
         "description":"database used for authentication"
      },
      "path":{
         "name":"$path",
         "description":"path to the repository / the revision"
      },
      "plugin_path":{
         "name":"$plugin_path",
         "description":"path to the plugins root folder"
      },
      "project_name":{
         "name":"$project_name",
         "description":"Name of the project"
      },
      "revision":{
         "name":"$revision",
         "description":"revision hash of the revision which is processed"
      }
   }
}
```
Besides that, I have three more questions would like to confirm with you:
1. Is visualSHARK's local db ('smartshark") the same local db in serverSHARK (in 'serverSHARK/server/settings_vagrant.py)? If so, I guess the user and the password shoudl be the same?
2. In "visualSHARK/sntest/settings.py", I'm not sure how to set up "SERVERSHARK_API_URL". the default url is 'http://127.0.0.1:8001/remote', do I just use it?
3. And also, how can I make sure the project created in serverSHARK by user A will be shown under user B's account in visualSHARK. Or if #1 is correct, user profiles are shared between visualSHARK and serverSHARK?

I feel very close to making serverSHARK and visualSHARK both work! After all done, please allow me to add some details to the readme :-).

Thank you!!!

**Comment by yiikou** [comment]
Ah, I check down to ```serverSHARK/smartshark/views/remote.py #44```, seems the failure of the visualSHARK worker is due to the unmatched API key. I've confirmed that the API key in ```serverSHARK/server/settings_vagrant.py``` is the same as ```visualSHARK/sntest/settings.py```, which are both number, ```123```. Any suggestions on setting the API key?

**Comment by yiikou** [comment]
Update, after debugging `serverSHARK/smartshark/views/remote.py`, I found that if the API-key is int type, it will be translated to str type in serverSHARK, while the int type API-key in serverSHARK, is till in type. And this cause the Unauthorized failure. 

Now my system info of visualSHARK shows ``` Worker connection: true
serverSHARK connection: true```!!!

But there still no data in the dashboard, is it due to the unmatch user profile? @atrautsch

**Comment by atrautsch** [comment]
I'll answer the questions first:
1. The MongoDB is the same, the serverSHARK orchestrates the plugins that collect the data into the MongoDB which visualSHARK visualizes. Both serverSHARK and visualSHARK have an additional MySQL Database which persists their own data.
2. That is correct, however the remote connection is not usable at the moment. The idea was to trigger serverSHARK jobs from visualSHARK but we changed the plugin orchestration code in serverSHARK somewhat so it may not work anymore. Plus I did not include feature flags in visualSHARK to disable such features it is still visible to admin users.
3. We do not currently have a centralized login, the users for both are separate, they are stored in the respective MySQL databases of serverSHARK and visualSHARK. We added some small ACL capability to visualSHARK but that is only to help manual labeling processes. You can just create the same users for serverSHARK and visualSHARK.
4. The order is not important, you could even start the visualSHARK frontend before the backend.

I am aware that the readme lacks information, if you have suggestions you are very welcome to help us improve it.

The dashboard view contains some more expensive operations if more larger projects are present in the MongoDB therefore it is not generated on the fly. You can run the create_project_stats which should generate the data and write it into the MySQL database for visualSHARK.
You should also run create_project_attributes which creates data for the MongoDB projects in the MySQL database so that visualSHARK can overlay some settings, e.g., is the project visible for all users.

**Comment by yiikou** [comment]
hi @atrautsch, thanks for the further explanation. If I understand it correctly, the last step to sync up data from serverSHARK is to run the create_project_stats. I didn't find the corresponding operation in visualSHARK. And I tried ```python manage.py create_project_stats``` and ```python manage.py create_project_attributes ```, but nothing shows up. So how should I create project stats in visualSHARK?

Thank you.

**Comment by yiikou** [comment]
Update, I found that the ```Project.objects``` in ```visualSHARK/visualSHARK/management/commands/create_project_stats.py``` #17 is an empty array. I guess that is the reason why ```python manage.py create_project_stats``` doesn't work? Do you have any suggestions on it?

Thank you.

**Comment by atrautsch** [comment]
The Project.objects should contain the projects which are available in the MongoDB.
Maybe it does not connect to the same MongoDB as the serverSHARK?

**Comment by yiikou** [comment]
I also doubt that, but I don't know how to confirm it. I try to use a wrong db setting and the ```runserver`` failed. Does it mean my current db setting is correct?
Btw, the db port in serverSHARK is 27017. While that is in the Vagrant VM, and the exposed port is 27018. Hence, I set 27018 as the db port in visualSHARK. Is it correct?

**Comment by atrautsch** [comment]
That depends, if you run the visualSHARK in the Vagrant VM you set 27017, if you use it outside of the VM you should use 27018.

**Comment by yiikou** [comment]
There are two mongodb configurations, mongodb_local and mongodb. So I assume mongodb should be the same as serverSHARK, right? and what is for the another one.

**Comment by atrautsch** [comment]
You are correct, mongodb is the one that is used. The mongodb_local is just a placeholder for local development.

**Comment by yiikou** [comment]
After I set the configuration of ```mongodb``` the same as serverSHARK, it start syncing. But it raised an error

```
[OK] Updating Stats for Project common.rdf
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/visualSHARK/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/visualSHARK/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/visualSHARK/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/visualSHARK/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/visualSHARK/visualSHARK/management/commands/create_project_stats.py", line 34, in handle
    for vcs in VCSSystem.objects.filter(project_id=pro.id):
  File "/visualSHARK/lib/python3.7/site-packages/mongoengine/queryset/queryset.py", line 99, in _iter_results
    self._populate_cache()
  File "/visualSHARK/lib/python3.7/site-packages/mongoengine/queryset/queryset.py", line 118, in _populate_cache
    self._result_cache.append(next(self))
  File "/visualSHARK/lib/python3.7/site-packages/mongoengine/queryset/base.py", line 1493, in __next__
    only_fields=self.only_fields)
  File "/visualSHARK/lib/python3.7/site-packages/mongoengine/base/document.py", line 722, in _from_son
    obj = cls(__auto_convert=False, _created=created, __only_fields=only_fields, **data)
  File "/visualSHARK/lib/python3.7/site-packages/mongoengine/base/document.py", line 78, in __init__
    raise FieldDoesNotExist(msg)
mongoengine.errors.FieldDoesNotExist: The fields "{'repository_file'}" do not exist on the document "VCSSystem"
```

**Comment by atrautsch** [comment]
In the virtualenv of the visualSHARK run pip install --upgrade pycoshark.

**Comment by yiikou** [comment]
it works!!!! Thank you! Let me explore the other functions.

**Comment by atrautsch** [comment]
No thats an error, it means that it could not fetch data from the VCSSystem collection. The visualSHARK backend should give you more information on that error.

**Comment by yiikou** [comment]
I got a similar error infor:
```
Internal Server Error: /vs/vcs/
Traceback (most recent call last):
  File "/visualSHARK/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/visualSHARK/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/visualSHARK/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/visualSHARK/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/visualSHARK/lib/python3.7/site-packages/rest_framework/viewsets.py", line 116, in view
    return self.dispatch(request, *args, **kwargs)
  File "/visualSHARK/lib/python3.7/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/visualSHARK/lib/python3.7/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/visualSHARK/lib/python3.7/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/visualSHARK/lib/python3.7/site-packages/rest_framework/mixins.py", line 42, in list
    page = self.paginate_queryset(queryset)
  File "/visualSHARK/lib/python3.7/site-packages/rest_framework/generics.py", line 173, in paginate_queryset
    return self.paginator.paginate_queryset(queryset, self.request, view=self)
  File "/visualSHARK/lib/python3.7/site-packages/rest_framework/pagination.py", line 337, in paginate_queryset
    return list(queryset[self.offset:self.offset + self.limit])
  File "/visualSHARK/lib/python3.7/site-packages/mongoengine/queryset/queryset.py", line 51, in __len__
    list(self._iter_results())
  File "/visualSHARK/lib/python3.7/site-packages/mongoengine/queryset/queryset.py", line 99, in _iter_results
    self._populate_cache()
  File "/visualSHARK/lib/python3.7/site-packages/mongoengine/queryset/queryset.py", line 118, in _populate_cache
    self._result_cache.append(next(self))
  File "/visualSHARK/lib/python3.7/site-packages/mongoengine/queryset/base.py", line 1493, in __next__
    only_fields=self.only_fields)
  File "/visualSHARK/lib/python3.7/site-packages/mongoengine/base/document.py", line 722, in _from_son
    obj = cls(__auto_convert=False, _created=created, __only_fields=only_fields, **data)
  File "/visualSHARK/lib/python3.7/site-packages/mongoengine/base/document.py", line 78, in __init__
    raise FieldDoesNotExist(msg)
mongoengine.errors.FieldDoesNotExist: The fields "{'repository_file'}" do not exist on the document "VCSSystem"
```

Do I need to update other packages?

**Comment by atrautsch** [comment]
Maybe you need to restart the backend process.

**Comment by yiikou** [comment]
When I checking the Commit graph tab, I got an error ```http://localhost:8000/vs/analytics/commitgraph/5fa406ff91416041b13a1113/```

I assume I need to run ```python manage.py create_commit_graph``` first? And the same for other function, I need to run corresponding job in advance?

**Comment by atrautsch** [comment]
Correct, the create_commit_graph needs to be run as a command for each project that you want to view the commit graph visualization of. I did not yet get around to implement dynamic offloading to the backend worker on requests from the frontend.

It should be python manage.py create_commit_graph projectname

**Comment by yiikou** [comment]
Cool, I can see the graph now.
